### ISSUE TITLE
Definir critérios da gamificação

### ISSUE THREAD

**Issue by matheusbsilva** [holandes-voador/gamificacao#11]
- [x] Definir recompensas
- [x] Definir quantidade de pontos por recompensa
- [x] Definir recuperação de recompensas
- [x] Definir peso das iterações:
  - [x] Por curtida
  - [x] Por comentário
  - [x] Por participação de eventos
- [x] Definir core drivers

**Comment by nukdown** [comment]
Algum progresso nessa issue @ZarathosDeath  e @rafaelhdo ?

**Comment by ZarathosDeath** [comment]
[Documentação de Gamificação - DAEng.docx](https://github.com/holandes-voador/gamificacao/files/2578825/Documentacao.de.Gamificacao.-.DAEng.docx)
Documento inicial do modelo de Gamificação
