### ISSUE TITLE
Manter usuário

### ISSUE THREAD

**Issue by matheusbsilva** [holandes-voador/gamificacao#6]
- [x] Criar usuário
  - [x] Informações necessárias
    - [x] Nome Completo
    - [x] E-mail
    - [x] Senha
    - [x] Curso
    - [x] Matrícula
    - [x] Pontos
- [x] Editar usuário
- [x] Deletar usuário
- [x] Visualizar usuário
- [x] Definir tipo do usuário

**Comment by nukdown** [comment]
a quantidade de pontos não deve ser atribuída pelo próprio usuário
